### PR TITLE
Feature/suggest repository

### LINKED ISSUE #172: Add "suggest a repository" button
**Is your feature request related to a problem? Please describe.**  
The list of repositories may not be exhaustive. It would be nice if users could "suggest" a repository to add to our list. This may also give us data to determine more popular areas that we are not servicing.

**Describe the solution you'd like**  
Some type of form (maybe a modal) that a user can fill out to suggest the addition of a new repository. I would suggest that the form be brief. We don't need every detail about a repository. That's research we can do on our own.

**Describe alternatives you've considered**  
N/A

### PR DESCRIPTION
**Pull request by bdaley**
Closes #172

### CODE REVIEW

**Comment by bdaley** [comment]
@samsonweiner Here's my feedback on this one:

*   [ ] The form should not submit without validation
*   [ ] I would reverse the order of the buttons for the sake of consistency.
*   [ ] Change the green button color to "primary"
*   [ ] Cancel should probably take you to the previous page
*   [ ] On second glance, we probably don't need a form for email address, since we already have it.
*   [ ] The field order is a little odd. Maybe: Name, Institution, Address, City, State, Country?
*   [ ] Confirm that this will actually send us an email.

**Comment by samsonweiner** [comment]
Rectified all issues except "I would reverse the order of the buttons for the sake of consistency" as I found the other forms had a similar setup (we can chat about this later). Also we decided to keep the email in incase they want to enter a separate email than their account.

**Comment by bdaley** [comment]
Looks good. The email is coming through, but it doesn't show all of the submitted fields:

**Pull request merged**
